apiVersion: v1
kind: ConfigMap
metadata:
  name: contextapi-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  ZONE: 'dev_sbx'

  # Redis
  REDIS_URL: 'redis-master.data'
  REDIS_USER: ''
  LOCAL_REDIS: 'false'

  # Postgres
  LIST_DB_NAME: 'list_db'
  DB_CLIENT: 'pg'
  DB_HOST: 'cxs-pg-pgbouncer.data'
  DB_USER: 'cxs-pg'
  DB_PORT: '5432'
  DB_NAME: 'ssp'
  DB_SSL: 'false'

  # Neo4j
  NEO4J_USER: 'neo4j'
  NEO4J_URI: 'neo4j://neo4j.data:7687'
  NEO4J_DATABASE: 'contextsuite'

  # Solr
  SOLR_PORT: '8983'
  SOLR_PATH: '/solr/quicklookup'
  SOLR_CORE: 'quicklookup'
  SOLR_COLLECTION: 'quicklookup'
  SOLR_HOST: 'solr.data'
  SOLR_PROTOCALL: 'http'

  # Clickhouse
  # CLICKHOUSE_CONNECTION: 'http://10.180.122.46:8123'
  CLICKHOUSE_CONNECTION: 'http://10.180.122.32:8123'
  CLICKHOUSE_USER: 'default'

  GRAPHQL_SERVER_PORT: '4001'
  GRAPHQL_SERVER_PATH: '/context'
  WKT_FOLDER: '/cdn/wkt_cache'

  # Sentry
  SENTRY_ENVIRONMENT: 'contextsuite-prod'
  NEXT_PUBLIC_SENTRY_DSN: 'https://97964f08ea76422f830fba0618967fc4@o982223.ingest.sentry.io/5937160'
  SENTRY_DSN: 'https://97964f08ea76422f830fba0618967fc4@o982223.ingest.sentry.io/5937160'
  HASH_SECRET: 'context-suite'
