apiVersion: v1
kind: Service
metadata:
  name: c001db2
  namespace: data
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: clickhouse-http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: clickhouse-native
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: port-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: c001db2
  namespace: data
  labels:
    kubernetes.io/service-name: c001db2
addressType: IPv4
ports:
  - name: postgres
    appProtocol: postgres
    protocol: TCP
    port: 5432
  - name: clickhouse-http
    appProtocol: clickhouse-http
    protocol: TCP
    port: 8123
  - name: clickhouse-native
    appProtocol: clickhouse-native
    protocol: TCP
    port: 9000
  - name: port-9092
    appProtocol: port-9092
    protocol: TCP
    port: 9092
endpoints:
  - addresses:
      - "10.180.122.46"
---
apiVersion: v1
kind: Service
metadata:
  name: c001db2
  namespace: api
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: clickhouse-http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: clickhouse-native
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: port-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: c001db2
  namespace: api
  labels:
    kubernetes.io/service-name: c001db2
addressType: IPv4
ports:
  - name: postgres
    appProtocol: postgres
    protocol: TCP
    port: 5432
  - name: clickhouse-http
    appProtocol: clickhouse-http
    protocol: TCP
    port: 8123
  - name: clickhouse-native
    appProtocol: clickhouse-native
    protocol: TCP
    port: 9000
  - name: port-9092
    appProtocol: port-9092
    protocol: TCP
    port: 9092
endpoints:
  - addresses:
      - "10.180.122.46"
---
apiVersion: v1
kind: Service
metadata:
  name: c001db2
  namespace: ingress
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: clickhouse-http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: clickhouse-native
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: port-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: c001db2
  namespace: ingress
  labels:
    kubernetes.io/service-name: c001db2
addressType: IPv4
ports:
  - name: postgres
    appProtocol: postgres
    protocol: TCP
    port: 5432
  - name: clickhouse-http
    appProtocol: clickhouse-http
    protocol: TCP
    port: 8123
  - name: clickhouse-native
    appProtocol: clickhouse-native
    protocol: TCP
    port: 9000
  - name: port-9092
    appProtocol: port-9092
    protocol: TCP
    port: 9092
endpoints:
  - addresses:
      - "10.180.122.46"
---
apiVersion: v1
kind: Service
metadata:
  name: c001db2
  namespace: pipelines
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: clickhouse-http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: clickhouse-native
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: port-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: c001db2
  namespace: pipelines
  labels:
    kubernetes.io/service-name: c001db2
addressType: IPv4
ports:
  - name: postgres
    appProtocol: postgres
    protocol: TCP
    port: 5432
  - name: clickhouse-http
    appProtocol: clickhouse-http
    protocol: TCP
    port: 8123
  - name: clickhouse-native
    appProtocol: clickhouse-native
    protocol: TCP
    port: 9000
  - name: port-9092
    appProtocol: port-9092
    protocol: TCP
    port: 9092
endpoints:
  - addresses:
      - "10.180.122.46"

