apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: storage
spec:
  ports:
    - name: minio
      protocol: TCP
      port: 9025
      targetPort: 9025
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: c001db1-minio
  namespace: storage
  labels:
    kubernetes.io/service-name: minio
addressType: IPv4
ports:
  - name: minio
    appProtocol: minio
    protocol: TCP
    port: 9025
endpoints:
  - addresses:
      - "10.180.122.32"
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: c001db2-minio
  namespace: storage
  labels:
    kubernetes.io/service-name: minio
addressType: IPv4
ports:
  - name: minio
    appProtocol: minio
    protocol: TCP
    port: 9025
endpoints:
  - addresses:
      - "10.180.122.46"
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: c001db3-minio
  namespace: storage
  labels:
    kubernetes.io/service-name: minio
addressType: IPv4
ports:
  - name: minio
    appProtocol: minio
    protocol: TCP
    port: 9025
endpoints:
  - addresses:
      - "10.180.122.3"
