apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  # The restore name ALSO becomes the tailscale hostname through the magic of YAML anchors
  name: &tailscale_hostname cxs-pg-restore-<YYYYMMDD>  # <-- always update this
  namespace: data
spec:
  expose:
    annotations:  # Expose theb restored cluster via tailscale:
      tailscale.com/expose: "true"
      tailscale.com/hostname: *tailscale_hostname  # <- Cunning use of yaml anchors
  dataSource:
    postgresCluster:
      clusterName: cxs-pg
      clusterNamespace: data
      repoName: repo1
      options:
        - --type=immediate
        - --db-include=ssp     # <-- sometimes update or omit this
        - --set=<snapshot_id>  # <-- always update this
  
  # Everything below this line can stay the same
  crVersion: 2.3.1
  users:
  - name: postgres
  - name: cxs-pg
    options: "SUPERUSER"
    databases:
      - ssp
  postgresVersion: 16
  image: percona/percona-postgresql-operator:2.3.1-ppg16-postgres

  imagePullPolicy: Always
  instances:
    - name: instance2
      replicas: 1
      dataVolumeClaimSpec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  
  proxy:  # required cruft. Omitting this caused the operator to crash
    pgBouncer:
      replicas: 1
      image: percona/percona-postgresql-operator:2.3.1-ppg16-pgbouncer
      exposeSuperusers: true
      config:
        global:
          max_client_conn: "200"
    
  backups:  # required cruft. CRD validation fails without this.
    pgbackrest:  
      image: percona/percona-postgresql-operator:2.3.1-ppg16-pgbackrest
      repos: 
      - name: repo2
        volume:
          volumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi

        
        