apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-analyser
spec:
  template:
    metadata:
      labels:
        instance: eu-north-1-production-default
        region: eu-north-1
        cluster: production
    spec:
      containers:
      - name: cep-analyser
        # Production resource limits
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 4000m
            memory: 4Gi
