apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llm-contextsuite-com-cert
  namespace: solutions
spec:
  secretName: llm-contextsuite-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "llm.contextsuite.com"