apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxsservices
spec:
  template:
    spec:
      containers:
      - name: node
        env:
        # Database credentials - migrate to dedicated database secrets
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse              # Dedicated ClickHouse secret
              key: admin-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cxs-pg-pguser-cxs-pg    # Matches POSTGRES_USER: 'cxs-pg'
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth              # Dedicated Redis secret
              key: redis-password
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxs-services-rag-worker
spec:
  template:
    spec:
      containers:
      - name: worker
        env:
        # Database credentials - migrate to dedicated database secrets
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse              # Dedicated ClickHouse secret
              key: admin-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cxs-pg-pguser-cxs-pg    # Matches POSTGRES_USER: 'cxs-pg'
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth              # Dedicated Redis secret
              key: redis-password
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords