apiVersion: apps/v1
kind: Deployment
metadata:
  name: synmetrix-hasura
spec:
  template:
    spec:
      containers:
      - name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: DATABASE_URL
        - name: HASURA_GRAPHQL_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: HASURA_GRAPHQL_JWT_SECRET
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synmetrix-cubejs
spec:
  template:
    spec:
      containers:
      - name: cubejs
        env:
        - name: CUBEJS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: POSTGRES_HOST
        - name: CUBEJS_DB_USER
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: POSTGRES_USER
        - name: CUBEJS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: POSTGRES_PASSWORD
        - name: CUBEJS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: POSTGRES_DB
        - name: CUBEJS_API_SECRET
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: CUBEJS_API_SECRET
        - name: CUBEJS_SECRET
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: CUBEJS_API_SECRET
        - name: CUBEJS_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: REDIS_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synmetrix-actions
spec:
  template:
    spec:
      containers:
      - name: actions
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: synmetrix-secrets
              key: DATABASE_URL 