apiVersion: v1
data:
  AIRFLOW_AUTH_USERNAME: admin
  AIRFLOW_DAG_ID: ingression
  AIRFLOW_GRACE_PERIOD: PT10M
  AIRFLOW_TRIGGER_URL: http://localhost:8082/api/v1/dags/ingression/dagRuns
  AVRO_SCHEMA_DIRECTORY: avro
  COAP_RESOURCE: sensors
  COAP_SERVER_URL: coap://localhost:5683/sensors
  GEOIP_BUCKET_NAME: geoip-bucket
  GEOIP_ENABLED: "true"
  GEOIP_FILE_NAME: GeoIP2-City.mmdb
  JWT_EXPIRATION: "3600000"
  JWT_REFRESH_EXPIRATION: "86400000"
  KAFKA_HOST: kafka-broker-0.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-1.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-2.kafka-broker-headless.data.svc.cluster.local:9092
  KAFKA_HOST_NEW: kafka-broker-1.kafka-broker-headless.data.svc.cluster.local:9092
  KAFKA_PORT: "9092"
  KAFKA_URI: kafka-broker-0.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-1.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-2.kafka-broker-headless.data.svc.cluster.local:9092
  KAFKA_URI_NEW: kafka-broker-1.kafka-broker-headless.data.svc.cluster.local:9092
  KAFKA_USER: user1
  MQTT_BROKER_URL: tcp://localhost:1883
  MQTT_CLIENT_ID: my-mqtt-client
  MQTT_TOPIC: iot-mqtt-updates
  NATS_KAFKA_TOPIC: iot-kafka-updates
  NATS_SERVER: nats://localhost:4222
  NATS_TOPIC: iot-updates
  NEO4J_DATABASE: contextsuite
  NEO4J_HOST: neo4j.data
  NEO4J_URI: neo4j://neo4j.data:7687
  NEO4J_USER: admin
  POSTGRES_DB: ssp
  POSTGRES_HOST: cxs-pg-ha.data
  POSTGRES_PORT: "5432"
  POSTGRES_USER: cxs-pg
  REDIS_DB: "0"
  REDIS_HOST: redis-master.data
  REDIS_LOCAL: "true"
  REDIS_PORT: "6379"
  REDIS_TTL: "120"
  S3_ENDPOINT: http://s-darz.cloud.gcore.lu:4566
  S3_REGION: s-darz
  SCHEMA_REGISTRY_ENABLED: "false"
  SCHEMA_REGISTRY_URL: http://data-kafka-schema-registry:8081
  SERVER_PORT: "9090"
  SPRING_PROFILES_ACTIVE: prod
  VAULT_ENABLED: "false"
  VAULT_HOST: vault-vault.data
  VAULT_PORT: "8200"
  VAULT_SCHEME: http
  VAULT_TOKEN: ingression
  WEBHOOK_BATCH_PROCESSING_INTERVAL: "5000"
  WEBHOOK_BATCH_SIZE: "100"
  WRITEKEY_HEADER_NAME: writekey
kind: ConfigMap
metadata:
  name: inbox-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inbox
    tier: api
  name: inbox
spec:
  ports:
  - name: http
    port: 9090
  - name: sftp
    port: 2222
  selector:
    app: inbox
    tier: api
  sessionAffinity: ClientIP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inbox
      tier: api
  template:
    metadata:
      labels:
        app: inbox
        tier: api
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: inbox-secrets
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              key: NEO4J_PASSWORD
              name: inbox-secrets
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: inbox-secrets
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: inbox-secrets
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: inbox-secrets
        - name: KAFKA_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KAFKA_USER_PASSWORD
              name: inbox-secrets
        - name: AIRFLOW_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AIRFLOW_AUTH_PASSWORD
              name: inbox-secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: inbox-secrets
        - name: VAULT_KV_BACKEND
          valueFrom:
            secretKeyRef:
              key: VAULT_KV_BACKEND
              name: inbox-secrets
        envFrom:
        - configMapRef:
            name: inbox-config
        image: quicklookup/inbox:v1.0.11
        name: inbox
        ports:
        - containerPort: 9090
          name: http
        - containerPort: 2222
          name: sftp
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        restartPolicy: Never
        volumeMounts:
        - mountPath: /tmp
          name: sftp
      imagePullSecrets:
      - name: dockerlock
      volumes:
      - hostPath:
          path: /data/local/sftp
        name: sftp
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inbox
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inbox
  targetCPUUtilizationPercentage: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inbox
spec:
  rules:
  - host: inbox.contextsuite.com
    http:
      paths:
      - backend:
          service:
            name: inbox
            port:
              number: 9090
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - inbox.contextsuite.com
    secretName: star-contextsuite-com
