apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
data:
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "cxs-pg-pgbouncer.data"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_POOL_SIZE: "3"
  DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"

  QUEUE_BULL_REDIS_HOST: "redis-master.data.svc"
  QUEUE_BULL_REDIS_DB: "3"
  N8N_PORT: "5678"
  N8N_PUSH_BACKEND: "sse"
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_BLOCK_ENV_ACCESS_IN_NODE: "true"
  N8N_DISABLE_PRODUCTION_MAIN_PROCESS: "true"

  WEBHOOK_URL: "https://flows.contextsuite.com"
  CODE_DISABLE_STDOUT: "true"
  SKIP_STATISTICS_EVENTS: "true"
  EXECUTIONS_MODE: "queue"
  # QUEUE_BULL_REDIS_HOST: "redis-master.data"
  N8N_PROTOCOL: "http"

  N8N_RUNNERS_ENABLED: "true"
  OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"
