apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-webhook
spec:
  replicas: 3
  selector:
    matchLabels:
      service: n8n-webhook
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: n8n-webhook
    spec:
      restartPolicy: Always
      containers:
        - name: webhook
          image: n8nio/n8n:1.84.3
          args: ["webhook"]
          env:
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: N8N_ENCRYPTION_KEY
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: QUEUE_BULL_REDIS_PASSWORD
          envFrom:
            - configMapRef:
                name: n8n-config

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-webhook
spec:
  type: ClusterIP
  selector:
    service: n8n-webhook
  ports:
    - port: 5678
