apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
spec:
  replicas: 6
  selector:
    matchLabels:
      service: n8n-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: n8n-worker
    spec:
      restartPolicy: Always
      containers:
        - name: worker
          image: n8nio/n8n:1.84.3
          args: ["worker", "--concurrency=6"]
          env:
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: N8N_ENCRYPTION_KEY
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n
                  key: QUEUE_BULL_REDIS_PASSWORD
          envFrom:
            - configMapRef:
                name: n8n-config