apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solutions

images:
  - name: quicklookup/translator-client
    newTag: 689eafa

resources:
  - ../../base
  - translator-client-config.yaml
  - translator-client-ingress.yml