apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

configMapGenerator:
  - name: grafana-longhorn-alerts
    files:
      - longhorn-rules.yaml=longhorn-rules.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: grafana-postgresql-backup-alerts
    files:
      - postgresql-backup-rules.yaml=postgresql-backup-rules.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"

    

resources: []