apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxs-mimir-api
spec:
  selector:
    matchLabels:
      app: cxs-mimir-api
      tier: api
  template:
    metadata:
      labels:
        app: cxs-mimir-api
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/cxs-mimir-api:0660e35
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
          volumeMounts:
            - name: ephemerala
              mountPath: /usr/local/share/fonts
            - name: ephemeralb
              mountPath: /cache
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /gpt-api/status/alive
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          readinessProbe:
            httpGet:
              port: 8000
              path: /gpt-api/status/ready
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 9
            failureThreshold: 6
          env:
            - name: AZURE_OPENAI_API_KEY_NOT_USED
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AZURE_OPENAI_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: OPENAI_API_KEY_MIMIR2
            - name: EVENTS_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: EVENTS_SERVER_KEY
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: REDIS_PASSWORD
            - name: CLICKHOUSE_PASSWORD_LLM
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CLICKHOUSE_PASSWORD_LLM
            - name: VOYAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: VOYAGE_API_KEY
            - name: UNSTRUCTURED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: UNSTRUCTURED_API_KEY
            - name: CONTEXT_SUITE_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CONTEXT_SUITE_JWT_SECRET_KEY
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: TAVILY_API_KEY
            - name: BLUE_USEREMAIL
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_USEREMAIL
            - name: BLUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_PASSWORD
            - name: BLUE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_BASE_URL
            - name: BLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_API_KEY
            - name: TRAVIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: TRAVIA_API_KEY
            - name: SFTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: SFTP_USERNAME
            - name: SFTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: SFTP_PASSWORD
            - name: TOKEN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: TOKEN_SECRET_KEY
            - name: CHAT_FRESHDESK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CHAT_FRESHDESK_API_KEY
            - name: BOKUN_PROD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BOKUN_PROD_API_KEY
            - name: FRESHCHAT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: FRESHCHAT_API_TOKEN
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: GOOGLE_MAPS_API_KEY
          envFrom:
            - configMapRef:
                name: cxs-mimir-api-config
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: ephemerala
          emptyDir:
            sizeLimit: 5Gi
        - name: ephemeralb
          emptyDir:
            sizeLimit: 5Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cxs-mimir-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cxs-mimir-api
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
