apiVersion: apps/v1
kind: Deployment
metadata:
  name: inbox
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: inbox
        image: quicklookup/inbox:staging
        env:
        # Ubuntu 24.04 compatibility - writable cache directories
        - name: MPLCONFIGDIR
          value: /cache/matplotlib
        - name: FONTCONFIG_CACHE
          value: /cache/fontconfig
        - name: XDG_CACHE_HOME
          value: /cache