apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
  - path: data-credentials.yaml
  - path: configmap-patch.yaml
  - path: autoscaler-patch.yaml
