apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-chat-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  API_ENDPOINT: "https://mimir.contextsuite.com"
  WSS_ENDPOINT: "wss://mimir.contextsuite.com"
