apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctx-suite-light
spec:
  selector:
    matchLabels:
      app: ctx-suite-light
      tier: app
  template:
    metadata:
      labels:
        app: ctx-suite-light
        tier: app
    spec:
      containers:
        - name: node
          image: quicklookup/ctx-suite-light:16955a6
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/status/ready
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          envFrom:
            - configMapRef:
                name: ctx-suite-light-config
      imagePullSecrets:
        - name: dockerlock
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ctx-suite-light
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctx-suite-light
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
