apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubejs-app
  template:
    metadata:
      labels:
        app: cubejs-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: growing-mouse
      containers:
        - name: cubejs-app
          image: cubejs/cube:v1.3.41
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: cube-config
          env:
            - name: CUBEJS_CACHE
              value: "false"
            - name: CUBEJS_PRE_AGGREGATIONS
              value: "false"
            - name: CUBEJS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cubejs-secrets
                  key: CUBEJS_API_SECRET
            - name: CUBEJS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cubejs-secrets
                  key: CLICKHOUSE_USER
            - name: CUBEJS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cubejs-secrets
                  key: CLICKHOUSE_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /cube/conf
      volumes:
        - name: config
          hostPath:
            path: /data/cubestore/conf
            type: DirectoryOrCreate
