apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: cxs-service-pvc
  name: cxs-service-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
