namespace: solutions

nameSuffix: "-v2"

resources:
  - cxs-services-deployment.yaml
  - cxs-services-service.yaml
  - cxs-services-volumes.yaml

configMapGenerator:
  - name: cxs-services-config
    files:
      - cxs-services-config.yaml

transformers:
  - add-version-label.yaml
