apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exchange
spec:
  template:
    spec:
      containers:
      - name: exchange
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cxs-pg-pguser-cxs-pg
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: redis-password
        - name: KAFKA_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
