apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: contextapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contextapi
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
