apiVersion: v1
kind: Service
metadata:
  name: cxs-cube-api
  labels:
    app: cxs-cube-api
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: cxs-cube-api
    tier: api

