remoteWrite:
  - url: "https://ingest.observe.skyvafnir.cloud/api/v1/write"

env:
  - name: VM_remoteWrite_basicAuth_username
    valueFrom:
      secretKeyRef:
        name: observation-basic-auth
        key: username

  - name: VM_remoteWrite_basicAuth_password
    valueFrom:
      secretKeyRef:
        name: observation-basic-auth
        key: password


config:
  scrape_configs:
    - job_name: vmagent
      static_configs:
        - targets: ["localhost:8429"]

    - job_name: postgresql-exporter
      static_configs:
        - targets: 
          - postgres-exporter-prometheus-postgres-exporter.monitoring.svc:80
    
    - job_name: 'kube-state-metrics'
      static_configs:
      - targets:
        - kube-state-metrics.monitoring.svc:8080
    
    - job_name: kubernetes-metrics
      metrics_path: /metrics
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node

    - job_name: kubelet
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
    
    - job_name: kubelet-resources
      scheme: https
      metrics_path: /metrics/resource
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node