apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-client
spec:
  selector:
    matchLabels:
      app: translator-client
      tier: web
  template:
    metadata:
      labels:
        app: translator-client
        tier: web
    spec:
      containers:
        - name: node
          image: quicklookup/translator-client:689eafa
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/status/ready
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
      imagePullSecrets:
        - name: dockerlock
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: translator-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: translator-client
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
