apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  template:
    spec:
      containers:
      - name: ingress
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cxs-pg-pguser-cxs-pg    # Matches POSTGRES_USER: 'cxs-pg'
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth              # Dedicated Redis secret
              key: redis-password
        - name: KAFKA_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
