apiVersion: v1
kind: Service
metadata:
  name: kafkaui
  labels:
    app: kafkaui
    tier: gui
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: kafkaui
    tier: gui
