apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-api
spec:
  selector:
    matchLabels:
      app: gpt-api
      tier: api
  template:
    metadata:
      labels:
        app: gpt-api
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/gpt-api:050f677
          resources:
            requests:
              cpu: 1000m
              memory: 8000Mi
            limits:
              cpu: 1000m
              memory: 8000Mi
          volumeMounts:
          - name: ephemerala
            mountPath: /usr/local/share/fonts
          - name: ephemeralb
            mountPath: /cache
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /gpt-api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 7
            failureThreshold: 7
          readinessProbe:
            httpGet:
              port: 8000
              path: /gpt-api/status/ready
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 8
            failureThreshold: 6
          env:
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AZURE_OPENAI_API_KEY
            - name: AZURE_OPENAI_API_KEY_gpt_4
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AZURE_OPENAI_API_KEY_gpt_4
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: OPENAI_API_KEY
            - name: OPENAI_API_KEY_SMARTDATA
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: OPENAI_API_KEY_SMARTDATA
            - name: FRESHDESK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CHAT_FRESHDESK_API_KEY
            - name: CHAT_FRESHDESK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CHAT_FRESHDESK_API_KEY
            - name: BOKUN_PROD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BOKUN_PROD_API_KEY
            - name: FRESHCHAT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: FRESHCHAT_API_TOKEN
            - name: EVENTS_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: EVENTS_SERVER_KEY
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: GOOGLE_MAPS_API_KEY
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: REDIS_PASSWORD
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AWS_SECRET_ACCESS_KEY
            - name: CLICKHOUSE_PASSWORD_LLM
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CLICKHOUSE_PASSWORD_LLM
            - name: VOYAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: VOYAGE_API_KEY
            - name: UNSTRUCTURED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: UNSTRUCTURED_API_KEY
            - name: CONTEXT_SUITE_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CONTEXT_SUITE_JWT_SECRET_KEY
            - name: BLUE_USEREMAIL
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_USEREMAIL
            - name: BLUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_PASSWORD
            - name: BLUE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_BASE_URL
            - name: BLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BLUE_API_KEY
            - name: MICROSOFT_CLIENT_SECRET_GOI
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: MICROSOFT_CLIENT_SECRET_GOI
            - name: MICROSOFT_CLIENT_SECRET_BLUE
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: MICROSOFT_CLIENT_SECRET_BLUE
            - name: TRAVIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: TRAVIA_API_KEY
            - name: MPLCONFIGDIR
              value: /cache/matplotlib
            - name: FONTCONFIG_PATH
              value: /usr/local/share/fonts
                  
          envFrom:
            - configMapRef:
                name: gpt-api-config
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: ephemerala
          emptyDir:
            sizeLimit: 5Gi
        - name: ephemeralb
          emptyDir:
            sizeLimit: 5Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gpt-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpt-api
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
