resources:
  - ../../base

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.70.0
    releaseName: tailscale-operator
    namespace: tailscale
    valuesFile: staging-values.yaml