apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-api
spec:
  template:
    spec:
      containers:
      - name: node
        env:
        # Database credentials - migrate to dedicated database secrets
        - name: CLICKHOUSE_PASSWORD_LLM
          valueFrom:
            secretKeyRef:
              name: clickhouse              # Dedicated ClickHouse secret
              key: admin-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth              # Dedicated Redis secret
              key: redis-password
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
