---
- name: Configure SASL/PLAIN Authentication for Kafka Cluster - Phase 1 (Config Deployment)
  hosts: data_nodes
  become: yes
  vars:
    kafka_home: /home/kafka/kafka
    kafka_config_dir: "{{ kafka_home }}/config"
    kafka_user: kafka
    kafka_group: kafka
    
  tasks:
    - name: Stop Kafka services on all nodes
      systemd:
        name: kafka
        state: stopped
      
    - name: Backup current server.properties
      copy:
        src: "{{ kafka_config_dir }}/kraft/server.properties"
        dest: "{{ kafka_config_dir }}/kraft/server.properties.backup-{{ ansible_date_time.epoch }}"
        remote_src: yes
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: '0644'
    
    - name: Create JAAS configuration file
      template:
        src: kafka_server_jaas.conf.j2
        dest: "{{ kafka_config_dir }}/kafka_server_jaas.conf"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: '0600'
      
    - name: Update server.properties for SASL authentication
      blockinfile:
        path: "{{ kafka_config_dir }}/kraft/server.properties"
        marker: "# {mark} SASL Authentication Configuration"
        block: |
          # SASL Authentication Configuration
          listeners=SASL_PLAINTEXT://:9092,CONTROLLER://:9093
          advertised.listeners=SASL_PLAINTEXT://{{ ansible_hostname }}:9092
          listener.security.protocol.map=CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
          sasl.enabled.mechanisms=PLAIN
          sasl.mechanism.inter.broker.protocol=PLAIN
          security.inter.broker.protocol=SASL_PLAINTEXT
          
          # Authorization
          authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
          super.users=User:{{ kafka_admin_user }}
          allow.everyone.if.no.acl.found=true
      
    - name: Backup current kafka.service
      copy:
        src: /etc/systemd/system/kafka.service
        dest: /etc/systemd/system/kafka.service.backup-{{ ansible_date_time.epoch }}
        remote_src: yes
        mode: '0644'
    
    - name: Update systemd service with KAFKA_OPTS
      lineinfile:
        path: /etc/systemd/system/kafka.service
        regexp: '^Environment='
        line: 'Environment="JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64" "KAFKA_OPTS=-Djava.security.auth.login.config={{ kafka_config_dir }}/kafka_server_jaas.conf"'
        insertafter: '^\[Service\]'
      
    - name: Reload systemd daemon on all nodes
      systemd:
        daemon_reload: yes
      
    - name: Deploy client configuration files
      template:
        src: "{{ item }}.j2"
        dest: "{{ kafka_config_dir }}/{{ item }}"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: '0644'
      loop:
        - client.properties
        - producer.properties
        - consumer.properties
    
    - name: Test SASL authentication (first node only)
      shell: "{{ kafka_home }}/bin/kafka-broker-api-versions.sh --bootstrap-server {{ ansible_hostname }}:9092 --command-config {{ kafka_config_dir }}/client.properties"
      register: sasl_test
      when: inventory_hostname == groups['data_nodes'][0]
      failed_when: false
      
    - name: Display SASL authentication test results
      debug:
        var: sasl_test.stdout_lines
      when: inventory_hostname == groups['data_nodes'][0] and sasl_test is defined
      
    - name: Test cluster connectivity from first node
      shell: "{{ kafka_home }}/bin/kafka-topics.sh --bootstrap-server c001db1:9092,c001db2:9092,c001db3:9092 --command-config {{ kafka_config_dir }}/client.properties --list"
      register: cluster_test
      when: inventory_hostname == groups['data_nodes'][0]
      failed_when: false
      
---
- name: Verify Configuration and Restart Kafka Cluster - Phase 2
  hosts: data_nodes
  become: yes
  tasks:
    - name: Verify server.properties contains SASL configuration
      lineinfile:
        path: "{{ kafka_home }}/config/kraft/server.properties"
        line: "listeners=SASL_PLAINTEXT://:9092,CONTROLLER://:9093"
        state: present
      check_mode: yes
      register: sasl_config_check
      vars:
        kafka_home: /home/kafka/kafka
      
    - name: Verify JAAS configuration file exists
      stat:
        path: "{{ kafka_home }}/config/kafka_server_jaas.conf"
      register: jaas_file_check
      vars:
        kafka_home: /home/kafka/kafka
        
    - name: Verify systemd service has KAFKA_OPTS
      lineinfile:
        path: /etc/systemd/system/kafka.service
        regexp: 'KAFKA_OPTS.*kafka_server_jaas.conf'
        state: present
      check_mode: yes
      register: systemd_config_check
      
    - name: Display configuration verification results
      debug:
        msg:
          - "SASL config present: {{ sasl_config_check.changed == false }}"
          - "JAAS file exists: {{ jaas_file_check.stat.exists }}"
          - "SystemD KAFKA_OPTS configured: {{ systemd_config_check.changed == false }}"
    
    - name: Pause for manual verification
      pause:
        prompt: |
          
          Configuration deployed to all nodes. Please verify:
          
          1. SASL config is present: {{ sasl_config_check.changed == false }}
          2. JAAS file exists: {{ jaas_file_check.stat.exists }}  
          3. SystemD KAFKA_OPTS configured: {{ systemd_config_check.changed == false }}
          
          Press ENTER to proceed with Kafka restart on all nodes, or Ctrl+C to abort.

---
- name: Restart Kafka Cluster - Phase 3
  hosts: data_nodes
  become: yes
  tasks:        
    - name: Start Kafka services on all nodes simultaneously
      systemd:
        name: kafka
        state: started
        enabled: yes
        
    - name: Wait for Kafka services to start
      wait_for:
        port: 9092
        host: "{{ ansible_hostname }}"
        delay: 15
        timeout: 120
      vars:
        kafka_home: /home/kafka/kafka
      
    - name: Verify all Kafka services are active
      shell: systemctl is-active kafka
      register: kafka_status
      failed_when: kafka_status.stdout != "active"
      
    - name: Test SASL authentication (first node only)
      shell: "{{ kafka_home }}/bin/kafka-broker-api-versions.sh --bootstrap-server {{ ansible_hostname }}:9092 --command-config {{ kafka_home }}/config/client.properties"
      register: sasl_test
      when: inventory_hostname == groups['data_nodes'][0]
      failed_when: false
      vars:
        kafka_home: /home/kafka/kafka
      
    - name: Display SASL authentication test results
      debug:
        var: sasl_test.stdout_lines
      when: inventory_hostname == groups['data_nodes'][0] and sasl_test is defined
      
    - name: Test cluster connectivity from first node
      shell: "{{ kafka_home }}/bin/kafka-topics.sh --bootstrap-server c001db1:9092,c001db2:9092,c001db3:9092 --command-config {{ kafka_home }}/config/client.properties --list"
      register: cluster_test
      when: inventory_hostname == groups['data_nodes'][0]
      failed_when: false
      vars:
        kafka_home: /home/kafka/kafka
      
    - name: Display cluster connectivity results
      debug:
        var: cluster_test
      when: inventory_hostname == groups['data_nodes'][0] and cluster_test is defined