---
- name: Verify SASL Configuration - Phase 2
  hosts: data_nodes
  become: yes
  vars_files:
    - ../group_vars/data_nodes.yml
  vars:
    kafka_home: /home/kafka/kafka
    
  tasks:
    - name: Validate required SASL authentication variables are defined
      assert:
        that:
          - vault_kafka_admin_password is defined
          - vault_kafka_admin_password | length > 0
          - kafka_admin_user is defined
          - kafka_admin_user | length > 0
        fail_msg: |
          Required SASL authentication variables are missing or empty.
          Verification cannot proceed without these variables defined in group_vars/data_nodes.yml.
        success_msg: "Required SASL authentication variables are defined for verification"

    - name: Verify server.properties contains SASL configuration
      lineinfile:
        path: "{{ kafka_home }}/config/kraft/server.properties"
        line: "listeners=SASL_PLAINTEXT://:9092,CONTROLLER://:9093"
        state: present
      check_mode: yes
      register: sasl_config_check
      
    - name: Verify JAAS configuration file exists
      stat:
        path: "{{ kafka_home }}/config/kafka_server_jaas.conf"
      register: jaas_file_check
        
    - name: Verify systemd service has KAFKA_OPTS
      shell: grep -q 'KAFKA_OPTS.*kafka_server_jaas.conf' /etc/systemd/system/kafka.service
      register: systemd_config_check
      failed_when: false
      changed_when: false
      
    - name: Display configuration verification results
      debug:
        msg:
          - "SASL config present: {{ sasl_config_check.changed == false }}"
          - "JAAS file exists: {{ jaas_file_check.stat.exists }}"
          - "SystemD KAFKA_OPTS configured: {{ systemd_config_check.changed == false }}"
    
    - name: Pause for manual verification
      pause:
        prompt: |
          
          Configuration deployed to all nodes. Verification results:
          
          1. SASL config present: {{ sasl_config_check.changed == false }}
          2. JAAS file exists: {{ jaas_file_check.stat.exists }}  
          3. SystemD KAFKA_OPTS configured: {{ systemd_config_check.changed == false }}
          
          You can now run ./verify-sasl-config.sh for detailed verification.
          
          Press ENTER to proceed with Kafka restart on all nodes, or Ctrl+C to abort.
      when: inventory_hostname == groups['data_nodes'][0]