apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inbox-contextsuite-com-cert
  namespace: ingress
spec:
  secretName: inbox-contextsuite-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "inbox.contextsuite.com"