apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: quicklookup/inbox
    newTag: main-1005197

# Production uses defaults from base - no patches needed