apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml

images:
  - name: quicklookup/inbox
    newTag: main-9cfb7ef

# Production uses defaults from base - no patches needed