apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-chat-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  API_ENDPOINT: "https://agents.contextsuite.com"
  WSS_ENDPOINT: "wss://agents.contextsuite.com"
  BOT_IDENTIFIER: "bonus_tester"
  AUTH_TRUST_HOST: "true"
