apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-chat-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  BROWSER_CHAT_API: "https://agents.contextsuite.com"
  BROWSER_APP_API: "https://agents.contextsuite.com"
  MIMIR_SERVER_API: "https://agents.contextsuite.com"
  BROWSER_CHAT_WSS_API: "wss://agents.contextsuite.com"
  BOT_IDENTIFIER: "skattur_agent_dev"
  AUTH_URL: "https://mimir.contextsuite.com"
  AUTH_TRUST_HOST: "true"
  CONTEXTSUITE_ADMIN_API: "https://admin.contextsuite.com"
