apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-router
  labels:
    app: cep-router
    tier: api
spec:
  replicas: 2  # Router can be scaled for HA
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cep-router
      tier: api
  template:
    metadata:
      labels:
        app: cep-router
        tier: api
    spec:
      containers:
      - name: cep-router
        image: quicklookup/cep-router
        # Image tag managed in overlays/*/kustomization.yaml
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
          # Database credentials (shared with inbox and analyser)
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: POSTGRES_PASSWORD
          # Redis credentials (shared with inbox)
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: REDIS_PASSWORD_EMM

        envFrom:
          - configMapRef:
              name: cep-router-config
      imagePullSecrets:
        - name: dockerlock
