---
# Prometheus scrape configuration for data layer nodes
# Add this to your existing Prometheus configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-data-layer-config
  namespace: monitoring
data:
  data-layer-scrape.yml: |
    # Data Layer Infrastructure Monitoring
    - job_name: 'data-layer-nodes'
      static_configs:
        - targets: 
          - 'c001db1:9100'
          - 'c001db2:9100'  
          - 'c001db3:9100'
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      
      # Add labels for better organization
      relabel_configs:
        - source_labels: [__address__]
          regex: '([^:]+):.*'
          target_label: instance
          replacement: '${1}'
        - source_labels: [__address__]
          regex: '([^:]+):.*'  
          target_label: datacenter
          replacement: 'cxs-eu1'
        - source_labels: [__address__]
          regex: '([^:]+):.*'
          target_label: node_role
          replacement: 'data-layer'
          
      # Metric relabeling for better organization  
      metric_relabel_configs:
        # Add cluster label to all metrics
        - source_labels: [__name__]
          target_label: cluster
          replacement: 'cxs-data-layer'