apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxs-docs
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cxs-docs
      tier: web
  template:
    metadata:
      labels:
        app: cxs-docs
        tier: web
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['chown', '-R', '1001:65533', '/app/data']
          volumeMounts:
            - name: docs-data
              mountPath: /app/data
          securityContext:
            runAsUser: 0
      containers:
        - name: docs
          command:
            - sh
            - -c
            - /app/init-data.sh && node /app/server.js --hostname 0.0.0.0
          image: quicklookup/cxs-utils:ce8f
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: cxs-docs
                key: OPENAI_API_KEY
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: cxs-docs
                key: GEMINI_API_KEY
          - name: AIRTABLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: cxs-docs
                key: AIRTABLE_API_KEY
          envFrom:
            - configMapRef:
                name: cxs-docs-config
          # Mount the persistent volume to /app/data
          volumeMounts:
          - name: docs-data
            mountPath: /app/data
      volumes:
      - name: docs-data
        persistentVolumeClaim:
          claimName: cxs-docs-pvc
      imagePullSecrets:
        - name: dockerlock

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cxs-docs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cxs-docs
  minReplicas: 1
  maxReplicas: 1  # This workload depends on a RWO PVC, so more than 1 pod is not possible
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70