apiVersion: v1
kind: Service
metadata:
  name: cxs-docs
  labels:
    app: cxs-docs
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: cxs-docs
    tier: web