apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: solutions

configMapGenerator:
  - name: playground-config
    behavior: replace
    literals:
      - ENVIRONMENT=staging
      - DOMAIN=contextsuite.dev
      - GRAPH_ENDPOINT=https://app.contextsuite.dev/context

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: playground
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 1
      - op: replace
        path: /spec/minReplicas
        value: 1
  - target:
      kind: Ingress
      name: playground
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "letsencrypt-prod"
      - op: replace
        path: /spec/rules/0/host
        value: "playground.contextsuite.dev"
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "playground.contextsuite.dev" 