apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exchange
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: exchange
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 60