apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exchange
spec:
  serviceName: exchange
  selector:
    matchLabels:
      app: exchange
      tier: api
  replicas: 2
  template:
    metadata:
      labels:
        app: exchange
        tier: api
    spec:
      containers:
      - name: exchange
        image: quicklookup/inbox
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9090
          name: http
        - containerPort: 2222
          name: sftp
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: POSTGRES_PASSWORD
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: NEO4J_PASSWORD
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: REDIS_PASSWORD
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: S3_SECRET_KEY
          - name: KAFKA_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: KAFKA_USER_PASSWORD
          - name: AIRFLOW_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: AIRFLOW_AUTH_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: JWT_SECRET
          - name: VAULT_KV_BACKEND
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: VAULT_KV_BACKEND
        envFrom:
          - configMapRef:
              name: exchange-config
        volumeMounts:
          - mountPath: /tmp
            name: sftp
          - mountPath: /data/dlq
            name: dlq-data
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: sftp
          hostPath:
            path: /data/local/sftp
  volumeClaimTemplates:
  - metadata:
      name: dlq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi