apiVersion: v1
kind: Service
metadata:
  name: cxs-anonymization
  labels:
    app: cxs-anonymization
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: cxs-anonymization
    tier: api
