apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: in-contextsuite-com-cert
  namespace: ingress
spec:
  secretName: in-contextsuite-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "in.contextsuite.com"