grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: grafana.contextsuite.dev
    root_url: https://grafana.contextsuite.dev
  database:
    type: postgres
    url: $__file{/etc/secrets/csx-secrets/db-url}
    ssl_mode: require

admin:
  existingSecret: "cxs-staging-monitoring-grafana"
  userKey: admin-user
  passwordKey: admin-password

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - grafana.contextsuite.dev
  tls:
    - hosts:
        - grafana.contextsuite.dev
      secretName: grafana-tls

extraSecretMounts:
  - name: csx-secrets
    mountPath: /etc/secrets/csx-secrets
    secretName: csx-secrets
    readOnly: true
    optional: false

service:
  annotations:
    tailscale.com/hostname: grafana-dev
    tailscale.com/expose: "true"

  extraConfigmapMounts:
    - name: grafana-longhorn-alerts
      mountPath: /etc/grafana/provisioning/alerting/longhorn-rules.yaml
      subPath: longhorn-rules.yaml
      configMap: grafana-longhorn-alerts
      readOnly: true

testFramework:
  enabled: false