apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inbox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inbox
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 70