apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inbox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: inbox
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60