apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inbox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: inbox
  maxReplicas: 1
  minReplicas: 0
  targetCPUUtilizationPercentage: 60