apiVersion: apps/v1
kind: Deployment
metadata:
  name: inbox
spec:
  selector:
    matchLabels:
      app: inbox
      tier: api
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 # old pod stays until the new one is ready
  template:
    metadata:
      labels:
        app: inbox
        tier: api
    spec:
      containers:
      - name: inbox
        image: quicklookup/inbox:main-d7f13f9
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9090
          name: http
        - containerPort: 2222
          name: sftp
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 8       # gives ~2 minutes for GeoIP catch-up after ready once
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:               # protects slow GeoIP bootstrap
          httpGet:
            path: /actuator/health/readiness
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 30      # ~10 minutes max for first GeoIP load
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: POSTGRES_PASSWORD
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: NEO4J_PASSWORD
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: REDIS_PASSWORD
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: S3_SECRET_KEY
          - name: KAFKA_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: KAFKA_USER_PASSWORD
          - name: AIRFLOW_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: AIRFLOW_AUTH_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: JWT_SECRET
          - name: VAULT_KV_BACKEND
            valueFrom:
              secretKeyRef:
                name: inbox-secrets
                key: VAULT_KV_BACKEND
        envFrom:
          - configMapRef:
              name: inbox-config
        volumeMounts:
          - mountPath: /tmp
            name: sftp
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: sftp
          hostPath:
            path: /data/local/sftp