resources:
  - ../../base/

namespace: monitoring

helmCharts:
  - name: prometheus-postgres-exporter
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: postgres-exporter
    version: 6.8.1
    namespace: monitoring
    valuesFile: values.yaml