namespace: tailscale

resources:
  - ../../base

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.84.3
    releaseName: tailscale-operator
    namespace: tailscale
    valuesFile: values.yaml