apiVersion: v1
kind: Service
metadata:
  name: cxs-embeddings
  labels:
    app: cxs-embeddings
    tier: api
  annotations:
    tailscale.com/expose: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: cxs-embeddings
    tier: api
