apiVersion: v1
kind: ConfigMap
metadata:
  name: contextsuite-config
data:
  ZONE: 'dev_sbx'

  # Redis
  REDIS_URL: 'redis-master.data'
  LOCAL_REDIS: 'true'

  # Required Services

  REACT_APP_GRAPH_API_URL: "/graph"
  REACT_APP_CONTEXT_API_ENDPOINT: "/context"
  REACT_APP_STATS_API_ENDPOINT: "/stats"

  GRAPHQL_SERVER_PORT: '4001'
  GRAPHQL_SERVER_PATH: '/context'
  WKT_FOLDER: '/cdn/wkt_cache'

  # NEXT_PUBLIC_GRAPH_API_KEY

  # MAPBOX
  REACT_APP_MAPBOX_DARK_TILE_URL: 'https://api.mapbox.com/styles/v1/ingiatlason/cl4eglwhb000614ld9jgxs50r/tiles/256/{z}/{x}/{y}@2x?access_token='
  REACT_APP_MAPBOX_LIGHT_TILE_URL: 'https://api.mapbox.com/styles/v1/ingiatlason/cleie5zek005901pvxxblfo6a/tiles/256/{z}/{x}/{y}@2x?access_token='

  # Default value for admin URL (overridden by overlays)
  NEXT_PUBLIC_CONTEXTSUITE_ADMIN_URL: 'https://admin.contextsuite.com'

  # Sentry configuraiton is set via overlays
