apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - autoscaler.yaml

configMapGenerator:
  - name: ingress-config
    literals:
      # Kafka - External cluster with SASL authentication
      - KAFKA_URI_OLD=kafka-broker-0.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-1.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-2.kafka-broker-headless.data.svc.cluster.local:9092
      - KAFKA_HOST_OLD=kafka-broker-0.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-1.kafka-broker-headless.data.svc.cluster.local:9092,kafka-broker-2.kafka-broker-headless.data.svc.cluster.local:9092
      - KAFKA_URI=c001db1.data.svc.cluster.local:9094,c001db2.data.svc.cluster.local:9094,c001db3.data.svc.cluster.local:9094
      - KAFKA_HOST=c001db1.data.svc.cluster.local:9094,c001db2.data.svc.cluster.local:9094,c001db3.data.svc.cluster.local:9094
      - KAFKA_PORT=9094
      - KAFKA_USER=user1
      # Redis
      - REDIS_HOST=redis-master.data
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_LOCAL=true
      # Postgres
      - POSTGRES_HOST=cxs-pg-pgbouncer.data
      - POSTGRES_URI=jdbc:postgresql://cxs-pg-pgbouncer.data:5432/ssp
      - POSTGRES_USER=cxs-pg
      # Neo4j
      - NEO4J_URI=neo4j://neo4j.data:7687
      - NEO4J_HOST=neo4j.data
      - NEO4J_USER=admin
      - NEO4J_DATABASE=contextsuite
      # S3
      - S3_REGION=ams3
      - S3_ENDPOINT=https://cxs.ingression.ams3.digitaloceanspaces.com
      # Spring
      - SPRING_PROFILES_ACTIVE=prod