apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: isl-hotel-streaming-client-pvc
  name: isl-hotel-streaming-client-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
