apiVersion: apps/v1
kind: Deployment
metadata:
  name: isl-hotel-streaming-client
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
