---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-migrations-config
data:
  config.yaml: |
    version: 2
    endpoint: http://synmetrix-hasura:8080
    metadata_directory: metadata
    seeds_directory: seeds
    actions:
      kind: synchronous
      handler_webhook_baseurl: http://synmetrix-actions:3000 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-migrations-job
  namespace: synmetrix
spec:
  
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: hasura-migrate
        image: quicklookup/synmetrix-hasura:latest
        workingDir: /hasura-migrations
        command:
        - /bin/sh
        - -c
        - |
          hasura-cli migrate apply --all-databases
          hasura-cli metadata apply
          hasura-cli seed apply -f 1708465495269_demoSeed.sql

        # envFrom:
        #   - configMapRef:
        #       name: synmetrix-config
        env:
          - name: ENABLE_TELEMETRY
            value: "false"
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: synmetrix-secrets
                key: HASURA_GRAPHQL_ADMIN_SECRET
          - name: HASURA_GRAPHQL_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: synmetrix-secrets
                key: DATABASE_URL
          - name: HASURA_GRAPHQL_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: synmetrix-secrets
                key: HASURA_GRAPHQL_JWT_SECRET

        volumeMounts:
          - name: hasura-migrations-config
            mountPath: /hasura-migrations/config.yaml
            subPath: config.yaml
      volumes:
        - name: hasura-migrations-config
          configMap:
            name: hasura-migrations-config
